app:
    version: @project.version@
logging:
    level:
        root: INFO
log4j2:
    formatMsgNoLookups: true
spring:
    datasource:
        url: jdbc:hsqldb:file:../db/content/cube
        driver: org.hsqldb.jdbc.JDBCDriver
        username: sa
        password:
    liquibase:
        change-log: classpath:liquibase/change-log/change-log-master.xml
